### ISSUE TITLE
react-navigation v5?

### ISSUE THREAD

**Issue by kevinsproles** [robinheinze/ignite-trivia#2]
Can't get the app to launch. Using:

npm install
npx react-native run-ios

fails with: 
```
Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `react-native-screens` 
from `.../git/ignite-trivia/node_modules/react-navigation-stack/lib/module/views/StackView/StackViewCard.js`: 
Module `react-native-screens` does not exist in the Haste module map
```

Looks like this repo is using react-navigation 3.0.0, however latest is 5.x: https://reactnavigation.org/

Maybe 3.x doesn't build anymore? Have you thought about updating this example repo?

**Comment by syahnur197** [comment]
can look into this repo: https://github.com/syahnur197/react-native-boilerplate

**Comment by tommy921092** [comment]
@syahnur197 thanks for your repo sharing, I cloned your code but when I pull the screen no questions are being fetched on my phone(android). But I can fetch the quesiton on ios/android studio. Do you know what is missing?

**Comment by syahnur197** [comment]
probably some configuration in your android, though I cant pinpoint exactly where

**Comment by robinheinze** [comment]
This repo is fully updated now for Ignite 6.0.0, including React Navigation 5.
