### ISSUE TITLE
Error in the tutorial

### ISSUE THREAD

**Issue by bruteforks** [robinheinze/ignite-trivia#31]
https://github.com/robinheinze/ignite-trivia/blob/master/app/config/config.dev.ts
tutorial says:
  API_URL = "https://opentdb.com/api.php"
but finished code shows:
  API_URL: "https://opentdb.com/api.php"

**Comment by bruteforks** [comment]
might as well put some other small mistakes here, since i'm going through tutorial. 

> Add an entry in en.json within the i18n folder for this screen’s text translations:

I think should be 

> Add an entry in en.ts within the i18n folder for this screen’s text translations:

**Comment by bruteforks** [comment]
`<Text text="question" tx={"questionScreen.header"} />`

should be:

`<Text text="question" tx={"questionScreen.title"} />`

**Comment by bruteforks** [comment]
some of my corrections may be incorrect, as i have no experience with this framework, or with typescript

> First, we’ll add our QuestionStore to the app/models/root-store/root-store.ts.

to

> First, we’ll add our QuestionStore to the app/models/RootStore.ts

then in the code

`import { QuestionStore, QuestionStoreModel } from "../question-store/question-store"`
to
`import { QuestionStore, QuestionStoreModel } from "./QuestionStore"`

**Comment by bruteforks** [comment]
```
  .views((self) => ({
    get allAnswers() {
      return shuffle(self.incorrectAnswers.concat([self.correctAnswer]))
    }
  )}  <----
```
to

```
 .views((self) => ({
    get allAnswers() {
      return shuffle(self.incorrectAnswers.concat([self.correctAnswer]))
    }
  })) <---
```

not applicable to many people but if you're not using VScode or don't have auto import turned on, you'll also need to add this to the imports:
`import shuffle from "lodash.shuffle"`

**Comment by bruteforks** [comment]
project is broken. very frustrating. Hope you guys put time into fixing it.

**Comment by cdanwards** [comment]
@bruteforks thanks for commenting. I'm taking a look at some of these issues.

**Comment by cdanwards** [comment]
@bruteforks all the issues with the project should be updated. Most of them were just small oversights when transitioning the tutorial to Ignite Maverick and some of the naming convention changes with that. 

Thanks for helping us keep the tutorial up to date!

**Comment by bruteforks** [comment]
nice!! thank you. hope it helped

**Comment by bruteforks** [comment]
@cdanwards this is the problem i ran into that made me give up on trying to fix. cloning and running this repo (not code from the tutorial)
the radio buttons don't work. everything else looks like its working fine. Imagine it has something to do with the old library. Didn't feel like investigating further. hope it helps

edit: running the command suggested didn't help

---

WARN  Warning: componentWillMount has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: RadioButtons
 WARN  Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: RadioButtons

**Comment by bruteforks** [comment]
![Kooha-2023-03-14-17-18-07](https://user-images.githubusercontent.com/116930331/225154964-275cd88e-a27f-422b-81f0-5ebc94fa4c35.gif)
